name: Static Code Analysis

on:
  workflow_dispatch:
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]
  # merge_group:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm, Node.js & Install dependencies
        uses: ./.github/actions/setup

      - name: Format
        run: pnpm format

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm, Node.js & Install dependencies
        uses: ./.github/actions/setup

      - name: Lint
        run: pnpm lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm, Node.js & Install dependencies
        uses: ./.github/actions/setup

      - name: Typecheck
        run: pnpm typecheck
