name: Test action

on:
  # workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm, Node.js & Install dependencies
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm build

      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_PROJECT_KEY: "TEST"

      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_PROJECT_KEY: "TEST"
          JIRA_TICKET_PLACEHOLDER: "{{SOME_PLACEHOLDER}}"
