name: Test action

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm, Node.js & Install dependencies
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm build

      - uses: ./
